-- SQL Script to insert subtopics from Fundamentos de circuitos elétricos dataset

-- Insert Subtopics
INSERT INTO prompts (id, subtopic_id, subject, prompt, system, messages, reference_documents, version, number_questions) VALUES

-- Topic 1
-- Subtopic 1
(1, 1, 'Definições Básicas', 'Gera uma questão de escolha múltipla em português sobre definições básicas da terminologia de circuitos elétricos. A pergunta deve testar o significado de termos como nó, ramo, malha, corrente e tensão, sem depender de um documento de apoio.', NULL, NULL, NULL, 1, 0),
(2, 1, 'Associação de Termos', 'Gera uma questão de escolha múltipla em português em que o aluno tenha de associar corretamente um termo de circuitos elétricos à respetiva definição. Usa linguagem simples e foca a terminologia essencial da análise de circuitos.', NULL, NULL, NULL, 1, 0),
(3, 1, 'Termo Correto', 'Gera uma questão de escolha múltipla em português que peça para identificar qual o termo técnico correto para descrever uma ligação, um percurso fechado ou uma grandeza elétrica. Evita cálculos e foca apenas a nomenclatura.', NULL, NULL, NULL, 1, 0),
(4, 1, 'Linguagem Técnica', 'Gera uma questão de escolha múltipla em português sobre a linguagem técnica usada em circuitos elétricos. A pergunta deve distinguir entre termos semelhantes e mostrar a diferença entre eles de forma conceptual.', NULL, NULL, NULL, 1, 0),
-- Subtopic 2
(5, 2, 'Soma Algébrica das Tensões', 'Gera uma questão de escolha múltipla em português sobre a Lei de Kirchhoff das Malhas, focando a ideia de soma algébrica das tensões num percurso fechado. Não uses cálculos numéricos; testa apenas o conceito.', NULL, NULL, NULL, 1, 0),
(6, 2, 'Condição de Percurso Fechado', 'Gera uma questão de escolha múltipla em português que peça ao aluno para reconhecer quando a Lei de Kirchhoff das Malhas se aplica. A pergunta deve relacionar a lei com um percurso fechado no circuito.', NULL, NULL, NULL, 1, 0),
(7, 2, 'Interpretação da KVL', 'Gera uma questão de escolha múltipla em português sobre a interpretação física da Lei de Kirchhoff das Malhas. A pergunta deve avaliar se o aluno entende que as subidas e quedas de tensão se equilibram numa malha.', NULL, NULL, NULL, 1, 0),
(8, 2, 'Identificação de Afirmação Correta', 'Gera uma questão de escolha múltipla em português em que o aluno deva escolher a afirmação correta sobre a Lei de Kirchhoff das Malhas. Inclui distratores conceptuais plausíveis e mantém a questão curta.', NULL, NULL, NULL, 1, 0),
-- Subtopic 3
(9, 3, 'Ordem dos Passos', 'Gera uma questão de escolha múltipla em português sobre a ordem correta dos passos do método das correntes nas malhas. A pergunta deve exigir que o aluno reconheça a sequência lógica do procedimento.', NULL, NULL, NULL, 1, 0),
(10, 3, 'Passo Seguinte', 'Gera uma questão de escolha múltipla em português que peça ao aluno para identificar qual é o próximo passo do método depois de selecionar as malhas e definir os sentidos das correntes.', NULL, NULL, NULL, 1, 0),
(11, 3, 'Etapa em Falta', 'Gera uma questão de escolha múltipla em português em que uma sequência do método aparece incompleta e o aluno tem de escolher o passo em falta. Foca a lógica sequencial e não o cálculo.', NULL, NULL, NULL, 1, 0),
(12, 3, 'Encadeamento Lógico', 'Gera uma questão de escolha múltipla em português sobre o encadeamento lógico dos passos do método por correntes de malha, desde a leitura do circuito até à interpretação final dos resultados.', NULL, NULL, NULL, 1, 0),
-- Subtopic 4
(13, 4, 'Fonte Entre Malhas', 'Gera uma questão de escolha múltipla em português sobre o tratamento de uma fonte de corrente colocada entre duas malhas. A pergunta deve avaliar o conceito de supermalha ou de restrição de corrente, sem cálculo numérico.', NULL, NULL, NULL, 1, 0),
(14, 4, 'Restrição de Corrente', 'Gera uma questão de escolha múltipla em português que peça ao aluno para identificar a consequência de uma fonte de corrente num ramo partilhado por malhas. Foca a restrição imposta pela fonte.', NULL, NULL, NULL, 1, 0),
(15, 4, 'Supermalha', 'Gera uma questão de escolha múltipla em português sobre o conceito de supermalha. A pergunta deve testar se o aluno sabe quando é necessário contornar uma fonte de corrente entre malhas.', NULL, NULL, NULL, 1, 0),
(16, 4, 'Fonte no Contorno', 'Gera uma questão de escolha múltipla em português sobre como tratar uma fonte de corrente localizada no contorno de uma malha. A questão deve ser conceptual e clara.', NULL, NULL, NULL, 1, 0),
-- Subtopic 5
(17, 5, 'Ramo Partilhado', 'Gera uma questão de escolha múltipla em português sobre a relação entre corrente de malha e corrente num ramo partilhado. A pergunta deve avaliar se o aluno entende que a corrente do ramo pode resultar da diferença entre malhas.', NULL, NULL, NULL, 1, 0),
(18, 5, 'Expressão da Corrente', 'Gera uma questão de escolha múltipla em português que peça ao aluno para identificar a expressão correta da corrente num ramo a partir das correntes de malha envolvidas. Não uses números, apenas relações conceptuais.', NULL, NULL, NULL, 1, 0),
(19, 5, 'Corrente de Ramo vs. Corrente de Malha', 'Gera uma questão de escolha múltipla em português que compare corrente de ramo e corrente de malha. O aluno deve reconhecer quando os valores coincidem e quando precisam de ser combinados.', NULL, NULL, NULL, 1, 0),
(20, 5, 'Componentes Partilhados', 'Gera uma questão de escolha múltipla em português sobre componentes partilhados entre malhas e a forma como isso altera a corrente no ramo. A questão deve ser conceptual e direta.', NULL, NULL, NULL, 1, 0),
-- Subtopic 6
(21, 6, 'Sentido Assumido', 'Gera uma questão de escolha múltipla em português sobre a interpretação do sentido assumido para uma corrente. A pergunta deve focar a convenção de sinais e o significado do resultado positivo ou negativo.', NULL, NULL, NULL, 1, 0),
(22, 6, 'Resultado Negativo', 'Gera uma questão de escolha múltipla em português que peça ao aluno para interpretar o que significa uma corrente calculada com valor negativo. A questão deve ser conceptual e não numérica.', NULL, NULL, NULL, 1, 0),
(23, 6, 'Direções Opostas', 'Gera uma questão de escolha múltipla em português sobre correntes com sentidos opostos. O aluno deve reconhecer como o sentido escolhido inicialmente influencia a leitura do resultado.', NULL, NULL, NULL, 1, 0),
(24, 6, 'Leitura Física do Sinal', 'Gera uma questão de escolha múltipla em português sobre a leitura física do sinal de uma corrente em circuitos. A pergunta deve ajudar a interpretar a direção real da corrente em relação ao sentido de referência.', NULL, NULL, NULL, 1, 0),

-- Topic 2
-- Topic 7
(25, 7, 'Número de Nós', 'Mostra o esquemático do circuito e pede ao aluno para identificar o número total de nós elétricos distintos existentes no circuito.', NULL, NULL, NULL, 1, 0),
(26, 7, 'Número de Ramos', 'Mostra o circuito e pergunta quantos ramos elétricos existem, considerando cada ligação entre dois nós como um ramo.', NULL, NULL, NULL, 1, 0),
(27, 7, 'Identificação de Componentes em Paralelo', 'Apresenta o circuito e pede ao aluno para identificar quais componentes estão ligados em paralelo, ou seja, entre os mesmos dois nós.', NULL, NULL, NULL, 1, 0),
(28, 7, 'Identificação de Ramos Paralelos', 'Mostra os ramos do circuito e pede ao aluno para identificar quais ramos estão ligados em paralelo. Os ramos que estão em paralelo compartilham Nós de incidência que podem ser conferidos na tabela dos ramos.', NULL, NULL, NULL, 1, 0),
(29, 7, 'Número de Malhas Principais / Número de Equações de Malha', 'Pede ao aluno para calcular o número de malhas principais do circuito com base na fórmula e no circuito apresentado.', NULL, NULL, NULL, 1, 0),
(30, 7, 'Número de Malhas Auxiliares / Fontes de Corrente Ideais', 'Mostra o circuito e pede ao aluno para determinar quantas malhas auxiliares existem associadas às fontes de corrente ideais.', NULL, NULL, NULL, 1, 0),
(31, 7, 'Leitura da Estrutura do Circuito', 'Apresenta o esquemático do circuito e pede ao aluno para identificar se os componentes estão ligados em série, em paralelo ou numa configuração mista.', NULL, NULL, NULL, 1, 0),
(32, 7, 'Identificação de Componentes Ligados ao Mesmo Nó', 'Mostra um nó do circuito e pede ao aluno para identificar quais componentes partilham esse nó em comum.', NULL, NULL, NULL, 1, 0),
(33, 7, 'Reconhecimento de Ligações Diretas', 'Apresenta o circuito e pede ao aluno para identificar quais componentes estão diretamente ligados entre si sem elementos intermédios.', NULL, NULL, NULL, 1, 0),
(34, 7, 'Identificação de Componentes Exclusivos de um Ramo', 'Apresenta a lista de ramos do circuito e pede ao aluno para identificar quais componentes pertencem exclusivamente a um único ramo.', NULL, NULL, NULL, 1, 0),
(35, 7, 'Interpretação da Tabela de Componentes', 'Mostra a tabela de componentes do circuito e pede ao aluno para interpretar os tipos de componentes presentes e respetivos valores nominais.', NULL, NULL, NULL, 1, 0),
-- Topic 8
(36, 8, 'Identificação de Componentes da Malha', 'Mostra a figura de uma malha específica e pede ao aluno para identificar todos os componentes pertencentes a essa malha.', NULL, NULL, NULL, 1, 0),
(37, 8, 'Identificação de Ramos da Malha', 'Apresenta o esquemático de uma malha e pede ao aluno para indicar quais os ramos que fazem parte dessa malha.', NULL, NULL, NULL, 1, 0),
(38, 8, 'Número de Componentes da Malha', 'Mostra uma malha do circuito e pede ao aluno para indicar quantos componentes existem nessa malha.', NULL, NULL, NULL, 1, 0),
(39, 8, 'Número de Ramos da Malha', 'Apresenta uma malha específica e pergunta quantos ramos pertencem à malha.', NULL, NULL, NULL, 1, 0),
(40, 8, 'Malha Principal', 'Mostra uma malha específica e pergunta ao aluno se essa malha pode ser considerada uma malha principal no contexto da análise por correntes de malha.', NULL, NULL, NULL, 1, 0),
(41, 8, 'Malha Auxiliar', 'Apresenta uma malha e pede ao aluno para indicar se essa malha deve ser tratada como uma malha auxiliar.', NULL, NULL, NULL, 1, 0),
(42, 8, 'Validação de Malha', 'Mostra um conjunto de ramos destacados no circuito e pergunta ao aluno se o percurso apresentado constitui uma malha válida.', NULL, NULL, NULL, 1, 0),
(43, 8, 'Identificação de Malhas Independentes', 'Apresenta várias malhas possíveis e pede ao aluno para selecionar quais são independentes entre si.', NULL, NULL, NULL, 1, 0),
(44, 8, 'Deteção de Malha Redundante', 'Mostra um conjunto de malhas do circuito e pede ao aluno para identificar qual delas é redundante relativamente às restantes.', NULL, NULL, NULL, 1, 0),
(45, 8, 'Cobertura do Circuito por Malhas', 'Apresenta um conjunto de malhas selecionadas e pergunta ao aluno se todas as regiões relevantes do circuito ficam cobertas por esse conjunto.', NULL, NULL, NULL, 1, 0),
(46, 8, 'Identificação de Componentes Partilhados Entre Malhas', 'Mostra duas malhas do circuito e pede ao aluno para identificar os componentes comuns a ambas.', NULL, NULL, NULL, 1, 0),
(47, 8, 'Identificação de Ramos Partilhados Entre Malhas', 'Apresenta duas malhas específicas e pede ao aluno para indicar quais os ramos partilhados entre elas.', NULL, NULL, NULL, 1, 0),
(48, 8, 'Identificação de Componentes Exclusivos da Malha', 'Mostra uma malha e pede ao aluno para identificar quais componentes pertencem exclusivamente a essa malha.', NULL, NULL, NULL, 1, 0),
(49, 8, 'Comparação Entre Malhas', 'Mostra duas malhas diferentes e pede ao aluno para indicar as principais diferenças entre elas em termos de ramos e componentes.', NULL, NULL, NULL, 1, 0),
(50, 8, 'Seleção de Conjunto Válido de Malhas', 'Apresenta vários conjuntos possíveis de malhas e pede ao aluno para selecionar o conjunto adequado para realizar a análise por correntes de malha.', NULL, NULL, NULL, 1, 0),
(51, 8, 'Reconhecimento de Supermalha', 'Mostra o circuito com destaque para duas malhas adjacentes e pergunta ao aluno se elas formam uma supermalha.', NULL, NULL, NULL, 1, 0),
(52, 8, 'Identificação de Fonte de Corrente Entre Malhas', 'Apresenta duas malhas vizinhas e pede ao aluno para identificar se existe uma fonte de corrente no ramo comum entre elas.', NULL, NULL, NULL, 1, 0),
(53, 8, 'Associação de Componentes à Malha Correta', 'Mostra um componente destacado no circuito e pede ao aluno para indicar a que malha ou malhas esse componente pertence.', NULL, NULL, NULL, 1, 0),
(54, 8, 'Número Total de Malhas', 'Mostra o circuito completo e pede ao aluno para identificar o número total de malhas existentes.', NULL, NULL, NULL, 1, 0),
(55, 8, 'Correspondência Entre Malha e Esquemático', 'Apresenta várias figuras de malhas e pede ao aluno para associar cada figura à identificação correta da malha correspondente.', NULL, NULL, NULL, 1, 0),
(56, 8, 'Identificação de Percurso Fechado', 'Mostra um percurso destacado no circuito e pede ao aluno para indicar se esse percurso constitui um caminho fechado válido para análise de malha.', NULL, NULL, NULL, 1, 0),
(57, 8, 'Deteção de Percurso Não Válido', 'Apresenta um conjunto de ramos destacados e pede ao aluno para identificar porque razão o percurso não constitui uma malha válida.', NULL, NULL, NULL, 1, 0),
(58, 8, 'Identificação da Menor Malha Possível', 'Mostra o circuito e pede ao aluno para identificar a menor malha fechada existente no esquemático.', NULL, NULL, NULL, 1, 0),
(59, 8, 'Análise de Sobreposição Entre Malhas', 'Apresenta duas ou mais malhas e pede ao aluno para identificar quais os elementos sobrepostos entre elas.', NULL, NULL, NULL, 1, 0),
(60, 8, 'Escolha de Malhas para Simplificação', 'Mostra várias opções de conjuntos de malhas e pede ao aluno para selecionar o conjunto que simplifica mais a análise do circuito.', NULL, NULL, NULL, 1, 0),
-- Topic 9
(61, 9, 'Equação de uma Malha', 'Mostra a figura de uma malha específica e pede ao aluno para escrever a equação KVL correspondente a essa malha.', NULL, NULL, NULL, 1, 0),
(62, 9, 'Sistema Completo de Equações', 'Mostra a sobreposição das malhas do circuito e pede ao aluno para escrever o sistema completo de equações de malha.', NULL, NULL, NULL, 1, 0),
(63, 9, 'Completa a Equação de Malha', 'Mostra a equação de malha com um espaço em branco e pede ao aluno para preencher o termo faltante.', NULL, NULL, NULL, 1, 0),
(64, 9, 'Identificação de Termos da Equação', 'Mostra uma equação de malha e pede ao aluno para identificar o significado físico de cada termo da equação.', NULL, NULL, NULL, 1, 0),
(65, 9, 'Resistor Partilhado Entre Malhas', 'Mostra duas malhas com um resistor comum e pede ao aluno para escrever a expressão correta da queda de tensão nesse resistor.', NULL, NULL, NULL, 1, 0),
(66, 9, 'Identificação de Componentes numa Equação', 'Apresenta uma equação de malha e pede ao aluno para identificar quais componentes do circuito contribuem para essa equação.', NULL, NULL, NULL, 1, 0),
(67, 9, 'Deteção de Erro de Sinal', 'Mostra uma equação KVL com um erro de sinal e pede ao aluno para identificar o termo incorreto.', NULL, NULL, NULL, 1, 0),
(68, 9, 'Deteção de Componente Omitido', 'Apresenta uma equação de malha incompleta e pede ao aluno para identificar qual componente foi omitido.', NULL, NULL, NULL, 1, 0),
(69, 9, 'Deteção de Componente Indevido', 'Mostra uma equação de malha e pede ao aluno para identificar qual componente não deveria aparecer nessa equação.', NULL, NULL, NULL, 1, 0),
(70, 9, 'Completar Equação de Malha', 'Apresenta uma equação KVL parcialmente preenchida e pede ao aluno para completar os termos em falta.', NULL, NULL, NULL, 1, 0),
(71, 9, 'Associação Entre Equação e Malha', 'Mostra várias equações e várias malhas e pede ao aluno para associar cada equação à malha correspondente.', NULL, NULL, NULL, 1, 0),
(72, 9, 'Validação de Equação KVL', 'Mostra uma equação proposta para uma malha e pede ao aluno para indicar se a equação está correta.', NULL, NULL, NULL, 1, 0),
(73, 9, 'Número de Equações Necessárias', 'Mostra o circuito e pergunta quantas equações independentes são necessárias para resolver o sistema por correntes de malha.', NULL, NULL, NULL, 1, 0),
(74, 9, 'Identificação de Equação Redundante', 'Apresenta um conjunto de equações de malha e pede ao aluno para identificar se existe alguma equação redundante.', NULL, NULL, NULL, 1, 0),
(75, 9, 'Equação de Restrição de Fonte de Corrente', 'Mostra um circuito com fonte de corrente entre malhas e pede ao aluno para escrever a equação de restrição associada.', NULL, NULL, NULL, 1, 0),
(76, 9, 'Equação de Supermalha', 'Mostra uma supermalha no circuito e pede ao aluno para escrever a equação KVL correspondente.', NULL, NULL, NULL, 1, 0),
(77, 9, 'Correspondência Entre Sistema e Circuito', 'Apresenta um sistema de equações e vários circuitos possíveis e pede ao aluno para identificar qual circuito corresponde ao sistema.', NULL, NULL, NULL, 1, 0),
(78, 9, 'Interpretação Física do Sistema', 'Mostra o sistema final de equações e pede ao aluno para interpretar o significado físico das correntes de malha presentes.', NULL, NULL, NULL, 1, 0),
(79, 9, 'Identificação de Correntes na Equação', 'Apresenta uma equação de malha e pede ao aluno para identificar quais correntes de malha aparecem na equação.', NULL, NULL, NULL, 1, 0),
(80, 9, 'Coeficiente de Corrente de Malha', 'Mostra uma equação KVL e pede ao aluno para identificar o coeficiente associado a uma corrente de malha específica.', NULL, NULL, NULL, 1, 0),
(81, 9, 'Soma de Resistências da Malha', 'Mostra uma malha do circuito e pede ao aluno para determinar qual deveria ser o coeficiente diagonal da corrente dessa malha.', NULL, NULL, NULL, 1, 0),
(82, 9, 'Termos Fora da Diagonal', 'Apresenta uma matriz do sistema de malhas e pede ao aluno para interpretar os termos fora da diagonal principal.', NULL, NULL, NULL, 1, 0),
(83, 9, 'Equação Correspondente à Sobreposição de Malhas', 'Mostra a imagem de sobreposição das malhas e pede ao aluno para identificar qual equação representa corretamente a interação entre malhas.', NULL, NULL, NULL, 1, 0),
(84, 9, 'Identificação de Fonte na Equação', 'Apresenta uma equação KVL e pede ao aluno para identificar qual termo representa a contribuição de uma fonte independente.', NULL, NULL, NULL, 1, 0),
(85, 9, 'Validação da Forma Matricial', 'Mostra uma matriz de coeficientes proposta e pede ao aluno para indicar se ela representa corretamente o sistema de malhas do circuito.', NULL, NULL, NULL, 1, 0),
(86, 9, 'Construção Parcial do Sistema', 'Mostra uma parte do circuito e pede ao aluno para construir apenas a equação correspondente a uma das malhas.', NULL, NULL, NULL, 1, 0),
(87, 9, 'Deteção de Equação Impossível', 'Apresenta uma equação incompatível com o circuito e pede ao aluno para justificar porque não pode corresponder à análise de malhas.', NULL, NULL, NULL, 1, 0),
(88, 9, 'Interpretação dos Resultados das Correntes', 'Mostra os valores finais das correntes de malha e pede ao aluno para identificar quais correntes têm sentido contrário ao inicialmente assumido.', NULL, NULL, NULL, 1, 0),
(89, 9, 'Identificação de Corrente Nula', 'Mostra os resultados das correntes de malha e pede ao aluno para identificar se alguma corrente é igual a zero.', NULL, NULL, NULL, 1, 0),
(90, 9, 'Correspondência Entre Correntes e Malhas', 'Apresenta os valores das correntes de malha e pede ao aluno para associar cada corrente à respetiva malha do circuito.', NULL, NULL, NULL, 1, 0),
-- Topic 7
(91, 10, 'Valor de Corrente de um Ramo', 'Mostra a tabela de correntes do circuito e pede ao aluno para indicar o valor da corrente num ramo específico.', NULL, NULL, NULL, 1, 0),
(92, 10, 'Identificação da Corrente com Maior Magnitude', 'Apresenta os valores das correntes dos ramos e pede ao aluno para identificar qual corrente possui maior magnitude.', NULL, NULL, NULL, 1, 0),
(93, 10, 'Identificação da Corrente com Menor Magnitude', 'Mostra os valores das correntes dos ramos e pede ao aluno para indicar qual corrente possui menor magnitude.', NULL, NULL, NULL, 1, 0),
(94, 10, 'Sentido da Corrente', 'Mostra o desenho de uma corrente de ramo e pede ao aluno para identificar o sentido assumido para essa corrente.', NULL, NULL, NULL, 1, 0),
(95, 10, 'Corrente Positiva ou Negativa', 'Apresenta o valor calculado de uma corrente e pede ao aluno para interpretar se o sentido assumido inicialmente está correto.', NULL, NULL, NULL, 1, 0),
(96, 10, 'Correspondência Corrente-Ramo', 'Mostra várias correntes identificadas no circuito e pede ao aluno para associar cada corrente ao respetivo ramo.', NULL, NULL, NULL, 1, 0),
(97, 10, 'Relação Entre Corrente de Ramo e Correntes de Malha', 'Mostra um ramo partilhado entre malhas e pede ao aluno para identificar a relação entre a corrente do ramo e as correntes de malha.', NULL, NULL, NULL, 1, 0),
(98, 10, 'Corrente Resultante de Duas Malhas', 'Apresenta um ramo comum entre duas malhas e pede ao aluno para calcular ou identificar a expressão da corrente resultante nesse ramo.', NULL, NULL, NULL, 1, 0),
(99, 10, 'Identificação de Corrente Nula', 'Mostra a tabela de correntes e pede ao aluno para identificar se existe algum ramo com corrente igual ou aproximadamente igual a zero.', NULL, NULL, NULL, 1, 0),
(100, 10, 'Comparação Entre Correntes', 'Apresenta os valores das correntes dos ramos e pede ao aluno para comparar duas correntes específicas.', NULL, NULL, NULL, 1, 0),
(101, 10, 'Ordenação das Correntes', 'Mostra os valores das correntes do circuito e pede ao aluno para ordenar as correntes por magnitude.', NULL, NULL, NULL, 1, 0),
(102, 10, 'Identificação do Ramo Mais Percorrido', 'Mostra a tabela de correntes e pede ao aluno para identificar qual ramo conduz a maior corrente.', NULL, NULL, NULL, 1, 0),
(103, 10, 'Interpretação Física da Corrente', 'Mostra uma corrente negativa num ramo e pede ao aluno para interpretar o significado físico desse resultado.', NULL, NULL, NULL, 1, 0),
(104, 10, 'Corrente Associada a uma Malha', 'Mostra as correntes de malha calculadas e pede ao aluno para identificar qual corrente está associada a uma malha específica.', NULL, NULL, NULL, 1, 0),
(105, 10, 'Validação de Corrente de Ramo', 'Apresenta uma corrente calculada para um ramo e pede ao aluno para indicar se o valor é consistente com as correntes de malha envolvidas.', NULL, NULL, NULL, 1, 0),
(106, 10, 'Deteção de Valor de Corrente Incorreto', 'Mostra uma tabela de correntes onde um dos valores foi alterado incorretamente e pede ao aluno para identificar o valor inconsistente.', NULL, NULL, NULL, 1, 0),
(107, 10, 'Identificação de Ramos Partilhados por Correntes', 'Mostra o circuito e pede ao aluno para identificar quais ramos possuem correntes resultantes da combinação de duas correntes de malha.', NULL, NULL, NULL, 1, 0),
(108, 10, 'Correspondência Entre Imagem e Corrente', 'Apresenta imagens de correntes destacadas no circuito e pede ao aluno para associar cada imagem ao nome correto da corrente.', NULL, NULL, NULL, 1, 0),
(109, 10, 'Leitura da Tabela de Correntes', 'Mostra a tabela de correntes e pede ao aluno para interpretar os valores e sentidos apresentados.', NULL, NULL, NULL, 1, 0),
(110, 10, 'Corrente em Componentes Específicos', 'Mostra um componente destacado no circuito e pede ao aluno para indicar qual corrente o atravessa.', NULL, NULL, NULL, 1, 0),
(111, 10, 'Comparação Entre Corrente de Ramo e Corrente de Malha', 'Apresenta uma corrente de ramo e pede ao aluno para indicar se ela corresponde diretamente a uma corrente de malha ou à combinação de várias.', NULL, NULL, NULL, 1, 0),
(112, 10, 'Identificação de Correntes Iguais', 'Mostra os valores das correntes dos ramos e pede ao aluno para identificar quais correntes possuem o mesmo valor.', NULL, NULL, NULL, 1, 0),
(113, 10, 'Análise do Sentido Relativo das Correntes', 'Mostra várias correntes no circuito e pede ao aluno para identificar quais possuem sentidos opostos.', NULL, NULL, NULL, 1, 0),
(114, 10, 'Determinação da Corrente Total', 'Mostra várias correntes convergindo num nó e pede ao aluno para determinar a corrente total associada ao nó.', NULL, NULL, NULL, 1, 0),
(115, 10, 'Identificação de Corrente Dominante', 'Apresenta os resultados das correntes do circuito e pede ao aluno para identificar qual corrente domina o comportamento do circuito.', NULL, NULL, NULL, 1, 0),
(116, 10, 'Análise da Distribuição de Correntes', 'Mostra o desenho geral das correntes do circuito e pede ao aluno para interpretar como a corrente se distribui pelos diferentes ramos.', NULL, NULL, NULL, 1, 0),
(117, 10, 'Interpretação do Valor Fasorial', 'Apresenta um valor de corrente em formato fasorial e pede ao aluno para interpretar a magnitude e fase associadas.', NULL, NULL, NULL, 1, 0),
(118, 10, 'Conversão para Forma Amigável', 'Mostra o valor fasorial de uma corrente e pede ao aluno para identificar a representação amigável correspondente.', NULL, NULL, NULL, 1, 0),
(119, 10, 'Identificação de Correntes em Paralelo', 'Mostra ramos em paralelo no circuito e pede ao aluno para analisar como a corrente se distribui entre eles.', NULL, NULL, NULL, 1, 0),
(120, 10, 'Validação Global das Correntes', 'Apresenta todas as correntes calculadas do circuito e pede ao aluno para verificar se os resultados são fisicamente coerentes.', NULL, NULL, NULL, 1, 0)

ON DUPLICATE KEY UPDATE
  subtopic_id = VALUES(subtopic_id),
  subject = VALUES(subject),
  prompt = VALUES(prompt),
  system = VALUES(system),
  messages = VALUES(messages),
  reference_documents = VALUES(reference_documents),
  version = VALUES(version),
  number_questions = VALUES(number_questions);