-- SQL Script to insert questions related to each subtopic
INSERT INTO questions (
  id, subtopic_id, rag_document_id, question_type, question_text, image, correct_answer, 
  incorrect_answer, feedback, difficulty, number_tries, number_corrects, rating_sum_teacher, rating_count_teacher
) VALUES

-- Subtopic 1: Unidades SI
( 1, 1, 1, 'EM', JSON_ARRAY('Qual das seguintes é uma unidade base do SI?','Qual das seguintes é uma unidade base do SI?'), NULL, JSON_ARRAY('Metro','Metro'), JSON_ARRAY(JSON_ARRAY('Newton', 'Joule', 'Litro'), JSON_ARRAY('Newton', 'Joule', 'Litro')), JSON_ARRAY('Lembra-te de consultar a lista oficial das unidades base do SI.','Lembra-te de consultar a lista oficial das unidades base do SI.'), 1, 0, 0, 0, 0),
( 2, 1, 1, 'EM', JSON_ARRAY('Quantas unidades base existem no SI?','Quantas unidades base existem no SI?'), NULL, JSON_ARRAY('7','7'), JSON_ARRAY(JSON_ARRAY('6', '8', '10'), JSON_ARRAY('6', '8', '10')), JSON_ARRAY('Pensa nas grandezas físicas fundamentais reconhecidas internacionalmente.','Pensa nas grandezas físicas fundamentais reconhecidas internacionalmente.'), 1, 0, 0, 0, 0),
( 3, 1, 1, 'EM', JSON_ARRAY('O que significa SI?','O que significa SI?'), NULL, JSON_ARRAY('Sistema Internacional','Sistema Internacional'), JSON_ARRAY(JSON_ARRAY('Sistema Integrado', 'Sistema Inovador', 'Sistema Indutivo'), JSON_ARRAY('Sistema Integrado', 'Sistema Inovador', 'Sistema Indutivo')), JSON_ARRAY('Este acrónimo é usado mundialmente para padronizar medições.','Este acrónimo é usado mundialmente para padronizar medições.'), 1, 0, 0, 0, 0),

-- Subtopic 2: Múltiplos e submúltiplos
( 4, 2, 1, 'EM', JSON_ARRAY('Qual o prefixo SI para deste algarismo?','Qual o prefixo SI para deste algarismo?'), 'img/query/scientific_notation.png', JSON_ARRAY('Mili','Mili'), JSON_ARRAY(JSON_ARRAY('Micro', 'Nano', 'Centi'), JSON_ARRAY('Micro', 'Nano', 'Centi')), JSON_ARRAY('Relembra os prefixos mais comuns do SI para valores pequenos.','Relembra os prefixos mais comuns do SI para valores pequenos.'), 1, 0, 0, 0, 0),
( 5, 2, 1, 'EM', JSON_ARRAY('O prefixo "kilo" corresponde a que potência de 10?','O prefixo "kilo" corresponde a que potência de 10?'), NULL, JSON_ARRAY('10^3','10^3'), JSON_ARRAY(JSON_ARRAY('10^6', '10^9', '10^2'), JSON_ARRAY('10^6', '10^9', '10^2')), JSON_ARRAY('Este prefixo é muito usado para múltiplos de mil.','Este prefixo é muito usado para múltiplos de mil.'), 1, 0, 0, 0, 0),
( 6, 2, 1, 'EM', JSON_ARRAY('Qual destes é um submúltiplo?','Qual destes é um submúltiplo?'), NULL, JSON_ARRAY('Micro','Micro'), JSON_ARRAY(JSON_ARRAY('Mega', 'Giga', 'Tera'), JSON_ARRAY('Mega', 'Giga', 'Tera')), JSON_ARRAY('Procura o prefixo que representa uma fração muito pequena.','Procura o prefixo que representa uma fração muito pequena.'), 1, 0, 0, 0, 0),
( 7, 2, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),

-- Subtopic 3: Algarismos significativos
( 8, 3, 1, 'EM', JSON_ARRAY('Quantos algarismos significativos tem o número 0,00450?','Quantos algarismos significativos tem o número 0,00450?'), NULL, JSON_ARRAY('3','3'), JSON_ARRAY(JSON_ARRAY('2', '4', '5'), JSON_ARRAY('2', '4', '5')), JSON_ARRAY('Atenção aos zeros à esquerda e à direita do número.','Atenção aos zeros à esquerda e à direita do número.'), 1, 0, 0, 0, 0),
( 9, 3, 1, 'EM', JSON_ARRAY('O número 1200 tem quantos algarismos significativos?','O número 1200 tem quantos algarismos significativos?'), NULL, JSON_ARRAY('2','2'), JSON_ARRAY(JSON_ARRAY('3', '4', '1'), JSON_ARRAY('3', '4', '1')), JSON_ARRAY('Considera se há ou não ponto decimal para determinar os significativos.','Considera se há ou não ponto decimal para determinar os significativos.'), 1, 0, 0, 0, 0),
( 10, 3, 1, 'EM', JSON_ARRAY('Qual destes números tem 4 algarismos significativos?','Qual destes números tem 4 algarismos significativos?'), NULL, JSON_ARRAY('0,1234','0,1234'), JSON_ARRAY(JSON_ARRAY('0,012', '12,3', '1,2'), JSON_ARRAY('0,012', '12,3', '1,2')), JSON_ARRAY('Conta todos os dígitos que transmitem informação sobre a precisão.','Conta todos os dígitos que transmitem informação sobre a precisão.'), 1, 0, 0, 0, 0),
( 11, 3, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),

-- Subtopic 4: Carga elétrica
( 12, 4, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 13, 4, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 14, 4, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 15, 4, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),

-- Subtopic 5: Tensão elétrica
( 16, 5, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 17, 5, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 18, 5, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 19, 5, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),

-- Subtopic 6: Corrente elétrica
( 20, 6, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 21, 6, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 22, 6, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0),
( 23, 6, 1, 'EM', JSON_ARRAY('Este é um exemplo de um texto de questão em PT','Este é um exemplo de um texto de questão em EN'), NULL, JSON_ARRAY('Resposta Correta PT','Resposta Correta EN'), JSON_ARRAY(JSON_ARRAY('Resposta Incorreta 1 PT', 'Resposta Incorreta 2 PT', 'Resposta Incorreta 3 PT','Resposta Incorreta 4 PT'), JSON_ARRAY('Resposta Incorreta 1 EN', 'Resposta Incorreta 2 EN', 'Resposta Incorreta 3 EN','Resposta Incorreta 4 EN')), JSON_ARRAY('Feedback PT','Feedback EN'), 1, 0, 0, 0, 0)

ON DUPLICATE KEY UPDATE
  subtopic_id = VALUES(subtopic_id),
  rag_document_id = VALUES(rag_document_id),
  question_type = VALUES(question_type),
  question_text = VALUES(question_text),
  image = VALUES(image),
  correct_answer = VALUES(correct_answer),
  incorrect_answer = VALUES(incorrect_answer),
  feedback = VALUES(feedback),
  difficulty = VALUES(difficulty),
  number_tries = VALUES(number_tries),
  number_corrects = VALUES(number_corrects),
  rating_sum_teacher = VALUES(rating_sum_teacher),
  rating_count_teacher = VALUES(rating_count_teacher);